### ISSUE TITLE
Looking Glass 500 Server Error :: Syntax error

### ISSUE THREAD

**Issue by austin25241** [inex/birdseye#20]
When I try to access the looking glass from IXP manager I get the error message "500 Server Error :: Syntax error"
When I try to access directly from the server hostname (with the option enabled in the appropriate .env file), I get "Whoops, looks like something went wrong."

I've checked the logs, and the log for lighttpd gives this error whenever I try to access from either api or direct:
"sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper"

I've added "www-data        ALL=(ALL)       NOPASSWD: /srv/birdseye/bin/birdc" to both /etc/sudoers and /etc/sudoers.d/birdseye

I am running Ubuntu 20.04 and Bird 2.0.7

**Comment by nickhilliard** [comment]
this is a configuration issue, not a bug. Can you move the discussion to the ixp manager users' mailing list?  Instructions here:

https://www.ixpmanager.org/support/mailing-lists
