### ISSUE TITLE
[feature request] graphing BGP route count

### ISSUE THREAD

**Issue by yang-dev** [inex/birdseye#3]
- show how many BGP sessions are configured with an ASN and how many of them are up
- show graph of routes received and routes filtered

example
http://bgp.as30071.net/AS714

**Comment by barryo** [comment]
Hi @yang-dev - while that's an interesting feature, I'm afraid it is out side the scope of what we consider appropriate for Birdseye right now.

This kind if information can easily be graphed using tools such as Graphite from the data Birdseye provides.
