### ISSUE TITLE
Some typos in the Readme.md file

### ISSUE THREAD

**Issue by LaochMumhain** [inex/birdseye#6]
<-- Bird is however lacking an API to allow IXPs to provide thise same looking glass type tools. More over, this also affects an IXP's ability to monitor these routing daemons and member sessions to them.

--> Bird is, however, lacking an API to allow IXPs to provide these same looking glass type tools. Moreover, this also affects an IXP's ability to monitor these routing daemons and member sessions to them.

**Comment by LaochMumhain** [comment]
Main one is "thise" --> "these" plus some missing commas around however and "Moreover" is a single word.

**Comment by nickhilliard** [comment]
fixed in 4f24ee5
